name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
   
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:19.8.1
    
    steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Install NPM dependencies
          run: npm install 
        - name: Build and Export
          run: npm run generate
