name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
   
jobs:
  build:
  
    runs-on: ubuntu-latest
    container: node:19.8.1
    
    steps:
        - uses: actions/checkout@v2
        - name: Build the Docker image
          run: docker build  -t genesis-v2/admin-ui .
